# Generated by Django 6.1 on 2026-08-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_verfied_doctorprofile_patientprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='licence_number',
            new_name='license_number',
        ),
    ]
